# Generated by Django 3.2.7 on 2021-09-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210923_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleExtraBoleta',
            new_name='DetalleExtra',
        ),
        migrations.RenameModel(
            old_name='DetalleBoleta',
            new_name='DetalleProducto',
        ),
        migrations.RenameModel(
            old_name='Extras',
            new_name='Extra',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
